# This pipeline defines top-level output stages.
stages:
  eval-report-template:
    cmd: jupytext --to ipynb eval-report.md
    deps:
      - eval-report.md
    outs:
      - eval-report.ipynb:
          cache: false

  eval-report:
    foreach:
      - ml-100k
      - ml-latest-small
      - ml-1m
      - ml-10m
      - ml-20m
      - ml-25m
      - ml-32m
    do:
      cmd: papermill -r dataset ${item} eval-report.ipynb eval-report.${item}.ipynb
      deps:
        - eval-report.ipynb
        - runs/${item}-Bias
        - runs/${item}-IIE
        - runs/${item}-UUE
        - runs/${item}-ALS
        - runs/${item}-FlexMF
        - runs/${item}-Pop
        - runs/${item}-III
        - runs/${item}-IALS
        - runs/${item}-FlexLMF
        - runs/${item}-FlexBPR
      outs:
        - eval-report.${item}.ipynb:
            cache: false
      metrics:
        - eval-metrics.${item}.json:
            cache: false

  render-report:
    foreach:
      - ml-100k
      - ml-latest-small
      - ml-1m
      - ml-10m
      - ml-20m
      - ml-25m
      - ml-32m
    do:
      cmd: jupyter nbconvert --to html eval-report.${item}.ipynb
      deps:
        - eval-report.${item}.ipynb
      outs:
        - eval-report.${item}.html
