# This pipeline defines top-level output stages.
stages:
  eval-report-template:
    cmd: jupytext --to ipynb eval-report.md
    deps:
      - eval-report.md
    outs:
      - eval-report.ipynb:
          cache: false

  eval-report:
    foreach:
      - ml100k
      - mlsmall
      - ml1m
      - ml10m
      - ml20m
      - ml25m
      - ml32m
    do:
      cmd: papermill -r dataset ${item} eval-report.ipynb eval-report.${item}.ipynb
      deps:
        - eval-report.ipynb
        - runs/${item}-Bias
        - runs/${item}-IIE
        - runs/${item}-UUE
        - runs/${item}-ALS
        - runs/${item}-Pop
        - runs/${item}-III
        - runs/${item}-IALS
      outs:
        - eval-report.${item}.ipynb:
            cache: false
      metrics:
        - eval-metrics.${item}.json:
            cache: false
