vars:
  - datasets:
      - ml-100k
      - ml-latest-small
      - ml-1m
      - ml-10m
      - ml-20m
      - ml-25m
      - ml-32m

    pipelines:
      - bias
      - popular
      - iknn-explicit
      - iknn-implicit
      - uknn-explicit
      - uknn-implicit
      - ease
      - als-explicit
      - als-implicit
      - flex-explicit
      - flex-logistic
      - flex-bpr
      - flex-warp

# This pipeline defines top-level output stages.
stages:
  split-data:
    foreach: ${datasets}
    do:
      cmd: lenskit data split --fraction=0.2 --min-train-interactions=1 -d data-split/${item} data/${item}
      deps:
        - data/${item}/
      outs:
        - data-split/${item}/

  # generate recommendations for test data
  generate-recs:
    matrix:
      data: ${datasets}
      pipeline: ${pipelines}
    cmd: python scripts/run-pipeline.py -d data-split/${item.data} -o runs/${item.data}/${item.pipeline} pipelines/${item.pipeline}.toml
    deps:
      - scripts/run-pipeline.py
      - pipelines/${item.pipeline}.toml
      - data-split/${item.data}/
    outs:
      - runs/${item.data}/${item.pipeline}/

  eval-report-template:
    cmd: jupytext --to ipynb eval-report.md
    deps:
      - eval-report.md
    outs:
      - eval-report.ipynb:
          cache: false

  eval-report:
    foreach: ${datasets}
    do:
      cmd: papermill -r dataset ${item} eval-report.ipynb eval-report.${item}.ipynb
      deps:
        - eval-report.ipynb
        - data-split/${item}/
        - runs/${item}/
      outs:
        - eval-report.${item}.ipynb:
            cache: false
      metrics:
        - eval-metrics.${item}.json:
            cache: false

  report-html:
    foreach: ${datasets}
    do:
      cmd: jupyter nbconvert --to html eval-report.${item}.ipynb
      deps:
        - eval-report.${item}.ipynb
      outs:
        - eval-report.${item}.html
