[project]
authors = ["Michael Ekstrand <mdekstrand@drexel.edu>"]
channels = ["conda-forge", "pytorch", "nvidia"]
description = "LensKit Demo Experiment"
name = "lk-demo-experiment"
platforms = ["osx-arm64", "linux-64", "win-64", "linux-aarch64"]
version = "2025.0.dev"

[tasks]

[dependencies]
python = "~=3.12.0"
# lenskit= "~=2025.1"
pandas = "~=2.0"
docopt-ng = ">=0.9"
dvc = "~=3.50"
dvc-webdav = "~=3.0"
dvc-s3 = "~=3.0"
dvc-azure = "~=3.0"
pyarrow = ">=14"
zstandard = "*"
notebook = "~=7.2"
papermill = "~=2.6"
jupytext = "~=1.16"
seaborn = "~=0.13.0"
humanize = "~=4.0"
statsmodels = "~=0.14.0"
# lenskit deps
pytorch = { version = "~=2.2" }
structlog = ">=24"
pyzmq = ">=24"

ruff = "*"

scipy = "~=1.10"
psutil = "*"
parquet-tools = "*"

[pypi-dependencies]
lenskit = { git = "https://github.com/lenskit/lkpy.git", subdirectory = "lenskit" }

[feature.cuda]
platforms = ["linux-64", "linux-aarch64"]
system-requirements = { cuda = "12" }

[feature.cuda.dependencies]
pytorch-gpu = "*"

[environments]
cuda = { features = ["cuda"] }
