[project]
authors = ["Michael Ekstrand <mdekstrand@drexel.edu>"]
channels = ["pytorch", "nvidia", "conda-forge"]
description = "LensKit Demo Experiment"
name = "lk-demo-experiment"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "2025.0.dev"

[tasks]

[dependencies]
python="~=3.12.0"
# lenskit= "~=2025.1"
pandas="~=2.0"
dvc ="~=3.50"
pyarrow=">=14"
zstandard="*"
notebook="~=7.2"
papermill="~=2.6"
jupytext="~=1.16"
seaborn="~=0.13.0"
humanize="~=4.0"
statsmodels="~=0.14.0"
pytorch="~=2.2"

ruff="*"

scipy="~=1.20"
psutil="*"

[pypi-dependencies]
lenskit = {path = "../lkpy/lenskit", editable = true}

[feature.cuda]
platforms = ["linux-64", "win-64"]

[feature.cuda.system-requirements]
cuda = "12"

[feature.cuda.dependencies]
pytorch-mutex={build="cuda"}

[environments]
cuda = {features = ["cuda"]}
