# This pipeline defines stages that control running and evaluating algorithms
# We define one stage per data set, using 'foreach' to iterate over the algorithms
# that we want to run on it.
#
# We can't really iterate over Cartesian products very easily in the DVC repetition
# system, so we do need to repeat a stage for each data set.
#
# You can make additional non-repeated stages to run one algorithm on one data set.
stages:
  run-explicit-model:
    matrix:
      data:
        - ml-100k
        - ml-latest-small
        - ml-1m
        - ml-10m
        - ml-20m
        - ml-25m
        - ml-32m
      model:
        - Bias
        - IIE
        - UUE
        - ALS
    cmd: python run-model.py -d data/${item.data} -o runs/${item.data}-${item.model} ${item.model}
    wdir: ..
    deps:
      - run-model.py
      - data/${item.data}
    outs:
      - runs/${item.data}-${item.model}

  run-implicit-model:
    matrix:
      data:
        - ml-100k
        - ml-latest-small
        - ml-1m
        - ml-10m
        - ml-20m
        - ml-25m
        - ml-32m
      model:
        - Pop
        - III
        - IALS
    cmd: python run-model.py -d data/${item.data} -o runs/${item.data}-${item.model} --no-predict ${item.model}
    wdir: ..
    deps:
      - run-model.py
      - data/${item.data}
    outs:
      - runs/${item.data}-${item.model}
