stages:
  split-ml100k:
    cmd: python split-data.py -o data-split/ml100k ml100k
    wdir: ..
    deps:
      - split-data.py
      - data/ml-100k.zip
    outs:
      - data-split/ml100k
    params:
      - random.seed

  split-ml1m:
    cmd: python split-data.py -o data-split/ml1m ml1m
    wdir: ..
    deps:
      - split-data.py
      - data/ml-1m.zip
    outs:
      - data-split/ml1m
    params:
      - random.seed

  split-mlsmall:
    cmd: python split-data.py -o data-split/mlsmall mlsmall
    wdir: ..
    deps:
      - split-data.py
      - data/ml-latest-small.zip
    outs:
      - data-split/mlsmall
    params:
      - random.seed

  split-ml10m:
    cmd: python split-data.py -o data-split/ml10m ml10m
    wdir: ..
    deps:
      - split-data.py
      - data/ml-10m.zip
    outs:
      - data-split/ml10m
    params:
      - random.seed

  split-ml20m:
    cmd: python split-data.py -o data-split/ml20m ml20m
    wdir: ..
    deps:
      - split-data.py
      - data/ml-20m.zip
    outs:
      - data-split/ml20m
    params:
      - random.seed

  split-ml25m:
    cmd: python split-data.py -o data-split/ml25m ml25m
    wdir: ..
    deps:
      - split-data.py
      - data/ml-25m.zip
    outs:
      - data-split/ml25m
    params:
      - random.seed

  split-ml32m:
    cmd: python split-data.py -o data-split/ml32m ml32m
    wdir: ..
    deps:
      - split-data.py
      - data/ml-32m.zip
    outs:
      - data-split/ml32m
    params:
      - random.seed
