[meta]
name = "iknn-explicit"

[options]
base = "std:topn-predict"

[components.scorer]
class = "lenskit.knn.ItemKNNScorer"

[components.scorer.config]
max_nbrs = 20
save_nbrs = 2500
min_nbrs = 2
feedback = "explicit"
