[meta]
name = "flex-bpr"

[options]
base = "std:topn"

[components.scorer]
class = "lenskit.flexmf.FlexMFImplicitScorer"

[components.scorer.config]
embedding_size = 32
epochs = 15
loss = "warp"
convolution_layers = 2
item_bias = false
