[meta]
name = "iknn-implicit"

[options]
base = "std:topn"

[components.scorer]
class = "lenskit.knn.ItemKNNScorer"

[components.scorer.config]
max_nbrs = 20
save_nbrs = 2500
min_nbrs = 2
feedback = "implicit"
